# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

guest = Array.new
guest[0] = Guest.create({ name: 'Michael & David', email: 'mtorres253@gmail.com', departure_city: 'San Francisco, CA' })
guest[1] = Guest.create({ name: 'JD & John', email: 'jamesdmeadow@gmail.com', departure_city: 'San Francisco, CA' })
guest[2] = Guest.create({ name: 'Ed & Peter', email: 'edkelmo@yahoo.com', departure_city: 'Chicago, IL' })
guest[3] = Guest.create({ name: 'JP & Artie', email: 'asameni@yahoo.com', departure_city: 'San Francisco, CA' })
guest[4] = Guest.create({ name: 'Terry', email: 'terry.hemphill@gmail.com', departure_city: 'San Francisco, CA' })
guest[5] = Guest.create({ name: 'Karen & Corbin', email: 'corkar@gmail.com', departure_city: 'San Francisco, CA' })
guest[6] = Guest.create({ name: 'Cassie & Matt', email: 'cboogie@dslextreme.com', departure_city: 'San Francisco, CA' })
guest[7] = Guest.create({ name: 'Edmundo & Carrie', email: 'ed.ortega@gmail.com', departure_city: 'Santa Cruz, CA' })
guest[8] = Guest.create({ name: 'DTL & Rich', email: 'dtl2@earthlink.net', departure_city: 'Palo Alto, CA' })
guest[9] = Guest.create({ name: 'Hersin & Don', email: 'hersinm@yahoo.com', departure_city: 'Los Angeles, CA' })
guest[10] = Guest.create({ name: 'Matt & Marty', email: 'mattandmarty@gmail.com', departure_city: 'Los Angeles, CA' })
guest[11] = Guest.create({ name: 'Laurelei & Jeff', email: 'laureleip@aol.com', departure_city: 'Seattle, WA' })
guest[12] = Guest.create({ name: 'Bobby', email: 'robertisaacson86@gmail.com', departure_city: 'San Francisco, CA' })
guest[13] = Guest.create({ name: 'Zack', email: 'zacksinclair@gmail.com', departure_city: 'San Francisco, CA' })
guest[14] = Guest.create({ name: 'Olivia & Kevin', email: 'ojovais@gmail.com', departure_city: 'San Francisco, CA' })
guest[15] = Guest.create({ name: 'Paul & Michelle', email: 'paultannenbaum@gmail.com', departure_city: 'San Francisco, CA' })
guest[16] = Guest.create({ name: 'Jen', email: 'jennifer.tamez@gmail.com', departure_city: 'San Francisco, CA' })
guest[17] = Guest.create({ name: 'Matt & Sime', email: 'matthew_patao@yahoo.com', departure_city: 'Honolulu, HI' })
guest[18] = Guest.create({ name: 'Dominic Corsaro', email: 'dominiccorsaro@gmail.com', departure_city: 'Columbus, Ohio' })
guest[19] = Guest.create({ name: 'Francine & Dan Corsaro', email: 'f.corsaro@sbcglobal.net', departure_city: 'Indianapolis, IN' })
guest[20] = Guest.create({ name: 'Jeff Torres', email: 'torresjeffrey@yahoo.com', departure_city: 'Chicago, IL' })
guest[21] = Guest.create({ name: 'Ann & Clifford Cua', email: 'ann.cua@co.maui.hi.us', departure_city: 'Makawao, HI' })
guest[22] = Guest.create({ name: 'Pat & Lisa', email: 'arpinemerling@verizon.net', departure_city: 'Seattle, WA' })
guest[23] = Guest.create({ name: 'Verena & Joe Alexander', email: 'rena15@hotmail.com', departure_city: 'Kahului, HI' })
guest[24] = Guest.create({ name: 'Wendy & Dan', email: 'wdotnguyen@gmail.com', departure_city: 'New York, NY' })
guest[25] = Guest.create({ name: 'Brian & Sue', email: 'brianteakin@gmail.com', departure_city: 'San Francisco, CA' })
guest[26] = Guest.create({ name: 'Jonathan', email: 'jhiro009@gmail.com', departure_city: 'New York, NY' })
guest[27] = Guest.create({ name: 'Mattison', email: 'mattison@servomarketing.com', departure_city: 'Portland, OR' })
guest[28] = Guest.create({ name: 'Ron & David', email: 'ron@servomarketing.com', departure_city: 'San Francisco, CA' })
guest[29] = Guest.create({ name: 'John', email: 'johnnycamo@gmail.com', departure_city: 'Portland, OR' })
guest[30] = Guest.create({ name: 'Midge & Rex Vogan', email: 'rex.vogan.1@facebook.com', departure_city: 'Seattle, WA' })
guest[31] = Guest.create({ name: 'Marilyn & John Lajara', email: 'lajara@comcast.net', departure_city: 'Orlando, FL' })
guest[32] = Guest.create({ name: 'Mary Jane Arpin', email: 'mjarpin@yahoo.com', departure_city: 'Orlando, FL' })
guest[33] = Guest.create({ name: 'Mary Beth & Eric', email: 'mbkramer@sbcglobal.net', departure_city: 'Santa Cruz, CA' })
guest[34] = Guest.create({ name: 'Chris & Dan', email: 'cgalotta@yahoo.com', departure_city: 'San Francisco, CA' })
guest[35] = Guest.create({ name: 'Michele Olem & Robert Linton', email: 'molem@comcast.net', departure_city: 'Wellfleet, MA' })
guest[36] = Guest.create({ name: 'Gary & Kate Olem', email: 'olemg@earthlink.net', departure_city: 'Irvine, CA' })
guest[37] = Guest.create({ name: 'Jean Pierre & Denise Riu', email: ' jpr@jriu.com', departure_city: 'Boston, MA' })
guest[38] = Guest.create({ name: 'Jessica & Nick Parish', email: 'jess.riu@gmail.com', departure_city: 'Hanford, CA' })
guest[39] = Guest.create({ name: 'Jaki Riu', email: 'jaki.riu@gmail.com', departure_city: 'Male, Maldives' })
guest[40] = Guest.create({ name: 'Cathy & John Pokorny', email: 'cathyp@jhpokorny.net', departure_city: 'Dover, MA' })
guest[41] = Guest.create({ name: 'Richard & Dawn Pokorny', email: 'Richp@jhpokorny.net', departure_city: 'Boston, MA' })
guest[42] = Guest.create({ name: 'Laura Pokorny Houck & Robert', email: 'rouck2013@hotmail.com', departure_city: 'Boston, MA' })
guest[43] = Guest.create({ name: 'Michael Riu', email: 'miker@mjrtech.com', departure_city: 'Boston, MA' })
guest[44] = Guest.create({ name: 'Agnes Riu', email: 'riu.agnes@wanadoo.fr', departure_city: 'Paris, France' })
guest[45] = Guest.create({ name: 'Sheila Olem & Family', email: 'saolem@verizon.com', departure_city: 'Herndon, VA' })
guest[46] = Guest.create({ name: 'Tanya & Matt', email: 'tanyastolurow@comcast.net', departure_city: 'Oakland, CA' })
guest[47] = Guest.create({ name: 'Allie and Donato', email: 'allie.frank@gmail.com', departure_city: 'Berkeley, CA' })
guest[48] = Guest.create({ name: 'Susanna & Arlo', email: 'susannakohn@me.com', departure_city: 'New York, NY' })
guest[49] = Guest.create({ name: 'Jonathan & Melissa', email: 'Jgriff212@gmail.com', departure_city: 'New York, NY' })
guest[50] = Guest.create({ name: 'Lexi Van Valkenburgh', email: 'lexivvc@gmail.com', departure_city: 'New York, NY' })
guest[51] = Guest.create({ name: 'Mallory & Bruce', email: 'Mallory.Johnson@ucsf.edu', departure_city: 'Berkeley, CA' })
guest[52] = Guest.create({ name: 'Joey & Ron', email: 'joey.taylor@ucsf.edu', departure_city: 'San Francisco, CA' })
guest[53] = Guest.create({ name: 'Larry & Terry', email: 'larrylmft@gmail.com', departure_city: 'San Francisco, CA' })
guest[54] = Guest.create({ name: 'Daniel Owens', email: 'danielowensmusic@gmail.com', departure_city: 'San Francisco, CA' })
guest[55] = Guest.create({ name: 'Pavel & Mack', email: 'paulnp@comcast.net ', departure_city: 'San Francisco, CA' })
guest[56] = Guest.create({ name: 'Jason & Chris', email: 'cpalumbo@gmail.com', departure_city: 'Los Angeles, CA' })
guest[57] = Guest.create({ name: 'Ryan & Erik', email: ' ryan.patrick.gray@gmail.com', departure_city: 'Portland, OR' })
guest[58] = Guest.create({ name: 'Chris Holleran', email: 'Christopherholleran@hotmail.com', departure_city: 'San Francisco, CA' })
guest[59] = Guest.create({ name: 'Eunice Stephens & Mark', email: 'Eunice.Stephens@ucsf.edu', departure_city: 'San Francisco, CA' })
guest[60] = Guest.create({ name: 'Matt', email: 'mskl1968@ yahoo.com', departure_city: 'New York, NY' })
guest[61] = Guest.create({ name: 'Chris & Qris', email: 'chrisweipert@hotmail.com', departure_city: 'San Francisco' })
guest[62] = Guest.create({ name: 'Bracken & Alice', email: 'brackenhendricks@gmail.com', departure_city: 'Bethesda, MD ' })
guest[63] = Guest.create({ name: 'Josh', email: 'joshua.g.dunn@gmail.com', departure_city: 'San Francisco, CA' })
guest[64] = Guest.create({ name: 'Hernan & Sean', email: 'Luduena@gmail.com', departure_city: 'Vellejo, CA' })
guest[65] = Guest.create({ name: 'Myra & Emily', email: 'myrafriel@gmail.com', departure_city: 'San Francisco, CA' })
guest[66] = Guest.create({ name: 'Claire & Elena', email: 'Cgfriel1@yahoo.com', departure_city: 'San Francisco, CA' })
guest[67] = Guest.create({ name: 'Mo & Coco', email: ' mophalon@gmail.com', departure_city: 'San Francisco, CA' })
guest[68] = Guest.create({ name: 'Walter & Michael', email: 'turcot9859@icloud.com', departure_city: 'San Francisco, CA' })
guest[69] = Guest.create({ name: 'Kane & Rossana', email: 'baccigalupi@gmail.com', departure_city: 'Richmond, CA' })
guest[69] = Guest.create({ name: 'James & Brad', email: 'piscosanfrancisco@gmail.com', departure_city: 'San Francisco, CA' })

guest.length.times do |i|
  Shortener::ShortenedUrl.generate("http://www.davidandmichael.com/?eeid=#{CGI::escape(guest[i].email_encrypted)}", guest[i])
end


Response.create([{adults: '2', children: '1', guest_id: '1', comments: 'awesome', coming: true, friday_reception: true}])